### ISSUE TITLE
Correct URL?

### ISSUE THREAD

**Issue by wienbarg** [SenorSmartyPants/jellyfin-nmt#10]
(Initially tested on PC)
Just to clarify that I got it right:
My URL to start Jellyfin NMT is 
192.168.2.89/nmt/login.php?id=e8379f2693c44382a21906ba4f6d6a88
In the previous version I didn't need to add the user ID - http://Server-IP/nmt/ was enough.
When I try http://server-IP/nmt/index.php I'm being redirected to login.php and Boom :-(
![image](https://user-images.githubusercontent.com/78422693/108756982-8f2bb200-7549-11eb-97c0-486bf39e82c9.png)

That also happens on PCH...

On top of that my Poppy gets logged out after some time. After watching an episode the same login page appears.

**Comment by SenorSmartyPants** [comment]
JF-NMT seems to think you're not logged in. 

And it's not getting a list of users from your system.

Either you don't have the APIKEY setup. Or you have no public users? 

There's currently no way to enter a password on JF-NMT, so I don't have a password on any of my JF users. Not an issue since it is not externally accessible.

I updated the directions on the github project homepage. Check your secrets.php against the example there.

**Comment by SenorSmartyPants** [comment]
I just pushed an update to login.php that includes some basic API and user setup error checking.

**Comment by wienbarg** [comment]
I'm new to Jellyfin and haven't figured out a lot.
A "public user" you say? I couldn't find anything about public users in jellyfin. But Emby seems to know them. Maybe it's a difference since Jellyfin was forked?
I have one user (no password) and he even can „manage the server".
Wait a sec... I just found an option "Hide this user from login screens". It was checked.
I will immediately try your new login.php!

**Comment by wienbarg** [comment]
Interesting:
With  "Hide this user from login screens" ON login.php shows users👍🏻
With api_url set to localhost (in secrets.php) there are no pictures👎🏻 funny
I will use 192.168.2.89:8096 from now on

btw I had added user_id in secrets.php. I will do my next tests without it:
Now when on login.php my only user ("jellyfin") is displayed and I can choose it👍🏻😃
Although occasionally I'm presented with login.php and the user list🤔 strange

It's getting late "here". Tomorrow I will let my wife play around and report back. I will also take a closer look at your speed-dial solution😁

**Comment by SenorSmartyPants** [comment]
user_id was for a previous version. Shouldn't be needed anymore.

JF-NMT clients will show up in your JF dashboard, and should report playback. Playback reporting does not support resuming at the moment.

**Comment by SenorSmartyPants** [comment]
> Although occasionally I'm presented with login.php and the user list🤔 strange

That is odd. On PCH reboot you will need to login again. And maybe after a couple days in chrome? But that's probably dependant on your webserver.

**Comment by SenorSmartyPants** [comment]
Don't use login.php as your starting page. use index.php

**Comment by wienbarg** [comment]
> user_id was for a previous version. Shouldn't be needed anymore.

OK Won't use it anymore👍🏻

> Don't use login.php as your starting page. use index.php

OK index.php it is 😉
But... by using login.php with ?id=USERID I don't have to choose the (only) user every time... Or will there be side effects?

- On PCH reboot you will need to login again.

I will keep an eye on this behaviour🔍 Maybe it is a "side effect"? 😉

**Comment by SenorSmartyPants** [comment]
using login.php?id=USERID might be fine.

**Comment by SenorSmartyPants** [comment]
> > Although occasionally I'm presented with login.php and the user list🤔 strange
> 
> That is odd. On PCH reboot you will need to login again. And maybe after a couple days in chrome? But that's probably dependant on your webserver.

I'm now remembering I did something to make sessions last longer on PCH, but can't remember exactly what ATM. I seem to recall it was something to do with the apache sessions provider. 

Do you get prompted to login again ever when browsing on a PC?

**Comment by wienbarg** [comment]
I was just looking at mod_session. But it isn't even loaded :-( 
I will enable it and face the new challenge🤦‍♂️
Strangely on PC it hasn't happend yet. Maybe it's the cache...

Did I mention that Jellyfin and Jellyfin-NMT run on the same Raspi 4? For JF-NMT I installed Apache... I'm not too experienced but I'm willing to learn☝🏻 😉

**Comment by SenorSmartyPants** [comment]
I run both on a Rockpi 4.
