### ISSUE TITLE
Different targets for HOME-button

### ISSUE THREAD

**Issue by wienbarg** [SenorSmartyPants/jellyfin-nmt#12]
The HOME-button always takes you to index.php. In my YAMJ (AEON)-implementation I was able to alter that behaviour.
e.g. when you're looking at a season of a TV show pressing HOME takes you to the season list. From there HOME led to "all TV shows". 
Yes, you can use the BACK-button. But on my Remote the BACK-button is very liitle and not easy to find in the dark...

In YAMJ it was a simple "href="../". In JF-NMT it's more difficult 😒

btw Can I change the label for a request?

**Comment by SenorSmartyPants** [comment]
Closed in version v0.4.5

Create a config_local.php based on config_local.example.php and customize $tvid_page_index and $tvid_page_back
