### ISSUE TITLE
Navigating seasons with >15 episodes 

### ISSUE THREAD

**Issue by wienbarg** [SenorSmartyPants/jellyfin-nmt#9]
When a season is displayed wirh Season.php going from episode 15 to 16 doesn't work for me :-(  I've tried almost every button on the remote.

**Comment by SenorSmartyPants** [comment]
Clicking down on episode 15 will move to the next page and episode 16.

Clicking right will move to the next page of episodes.

Clicking left will move to the previous page.

Clicking up from the first episode on a page will not move to previous page. This is a bug.

Glad to know someone is trying out this software.

**Comment by SenorSmartyPants** [comment]
You can also use the number keypad on remote to type in an episode number and go to it (on currently visible page)

**Comment by wienbarg** [comment]
[... Glad to know someone is trying out this software. ...] It's **me** who is glad that I stumbled over it :-D
Our A- and C200 with YAMJ are already 10 years old but doing their job perfectly. With thetvdb changing their API I was desperate to find a replacement.
Your tool looks very very promising!

**Comment by wienbarg** [comment]
I found the "left" and "right" in the php-file but on my PCH nothing happens.
Also, in the webbrowser (with PCMENU = true;) going to the next page doesn't work...
Wait a sec. I will try it with internet explorer ;-) (JavaScript...)

**Comment by wienbarg** [comment]
IE was worse. Back to Chrome...
clickUp and clickDown works on the PC. The title, the picture and recap are displayed. But the episode list doesn't change from 1-15 to 16-last. Tomorrow I will give the A210 another chance.

**Comment by SenorSmartyPants** [comment]
I didn't realize you were trying on PC. All the directions I gave are when using on the PCH.

When using the PC you can mouse over the episodes to change the focus. Mouse over the episode page numbers to change pages.

**Comment by wienbarg** [comment]
I use the PC only to check the code and to understand what is going on ;-)
Right now I'm focused on Season.php: „Left“ and “right“ works.
But I'm still struggling with episodes 16+ :-(

**Comment by SenorSmartyPants** [comment]
Still struggling to understand how the code works? I'm not the original author of most of the JavaScript code. It's basically rewriting the episode list based on the multiple arrays that store the entire list of episodes on paging. It's a little convoluted to get it to work on PCH which has more limitations that a modern browser. 

Please let me know if episode paging works for you on your PCHs. If it does please close this issue. Thanks.

**Comment by wienbarg** [comment]
[… I'm not the original author of most of the JavaScript code. …]
;-) Thought so. But that's OK. Maybe I can add a little… 
[… Please let me know if episode paging works for you on your PCHs. If it does please close this issue. Thanks. …]
Give me a few days. Maybe I will find a way to make it work or I'll why it doesn't for me :-D

**Comment by wienbarg** [comment]
New finding: toggleright/toggleleft do work! I didn't realize it because the episodelist isn't refreshed and is showing the first 15 episodes the whole time! With clickup and clickdown title, recap and picture change to those of episodes 16 to last.🙄😱
Next step for me: changing the episodelist after toggleright.

**Comment by SenorSmartyPants** [comment]
What are you testing on? PC? NMT A(100? 200?) C200?

I only have a A-100. I made sure I had all the paging code checked on github, and I do. So obviously this is only tested on A-100.

If you are testing on a PCH and the episodelist is not updating, can you load up the same page on PC and see if the episode list updates there when you mouse over the "1/2 (18)" episode page indicator.

If it doesn't page there, save that HTML from chrome and send it to me.

**Comment by SenorSmartyPants** [comment]
Also, have you ever tried the YAMJ skins this software is based on? Do they work properly on your NMTs?

All the TV stuff is based on AiO_SabishGT_beta

**Comment by wienbarg** [comment]
I have one A210 and another C200. But I don't think that the browser behaves differently than on the A110s.
The skin I use for years is called "ÆON Movie Wall YAMJ" [(http://www.networkedmediatank.com/showthread.php?tid=25534)](http://www.networkedmediatank.com/showthread.php?tid=25534) with minor alterings by me.
My Tasks for the next weekend are A) Trying to get SabishGT to work [Forum link](http://www.networkedmediatank.com/showthread.php?tid=42467) and B) Searching for one of my old A110s and hope it's still running.

Regarding Chrome-output: No paging, sorry. Not when "mouseover" occuts and not by clicking  on "Next Page" (const PCMENU=true).

**Comment by SenorSmartyPants** [comment]
Try with PCMENU=false . I never had it set to true developing this. I preferred to make it so it "would just work" on PC as well.

**Comment by wienbarg** [comment]
**WTF???** I am the greatest **idiot** ever**!!!**
I used the wrong files. The whole time.
How do I get the newest version? 5 Minutes ago I discovered
![image](https://user-images.githubusercontent.com/78422693/108271498-30dd8880-7171-11eb-95a7-768997d93bfc.png)

Is that corrrect?
I put it on the webserver in „nmt2“ and: The f*** paging is there! At least in chrome -poppy must wait til tomorrow.
I will now turn back time (4 days should be enough) and start all over again.🤢😡🤬
I am so sorry that I wasted your time.
I'll be back in a few days😪😪😪

**Comment by SenorSmartyPants** [comment]
How did you get the source before?

Yes, that link will have the latest and greatest. (Which I haven't changed in a while)

**Comment by wienbarg** [comment]
I have no idea. I just found a "jellyfin-nmt-0.1.0.zip" in my download directory. Is that filename familiar to you?
It is a total miracle!

**Comment by wienbarg** [comment]
Found it. :-( Since I'm a github noob I accidentally got into"tags" and didn't realise that 0.1.0 was an old version...
Like I said before: idiot!
Can we please start fresh in a few days? ;-)

**Comment by SenorSmartyPants** [comment]
Not a problem. That was the one release I made, but lots of changes since then. Even Jellyfin playback reporting. There's some setup to get that working. Mostly just an API key from JF I think.

**Comment by wienbarg** [comment]
Wow, with the correct version everything works like a charm! Kudos. Lots of them 😃
I had some trouble with what URL to start, but a little trial and error did it. 😉
Thx a lot.
